spring:
  application:
      name: advisio-core
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: audit
    default-schema: advisio_core
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1000000000000000
  security:
    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: advisio-spring-app
##            client-secret: eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxZGM4ZjUzYS1lYTA5LTRiMmMtYmE5Mi1hMDM0ZTg2NDhjYjQifQ.eyJleHAiOjE3ODYwMTcwMjcsImlhdCI6MTc1NDQ4MTAyNywianRpIjoiZWQ0OGI0MDUtZTM2OC00OTFkLWE1MGYtN2U4ZTQ4ODljNTAyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9hZHZpc2lvX3JlYWxtIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9hZHZpc2lvX3JlYWxtIiwidHlwIjoiSW5pdGlhbEFjY2Vzc1Rva2VuIn0.CPfm8kppg9W9Q5d_dI5mlqcLMGw3Q8Z324hwGaQ4G4w0zBtb2zOxZREVwtwS3VBE5Eoo5bncaQQQV7bTT1ulUQ  # Найти в Keycloak → Clients → spring-app → Credentials
#            scope: openid,profile,email
#            provider: keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/advisio_realm
#            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

keycloak:
  auth-server-url: http://localhost:8080
  realm: advisio_realm
keycloak-admin:
  client-id: admin-cli
  client-secret: your-client-secret
  username: admin
  password: admin

aws:
  accessKeyId: pZHFL6TARutSLZ1E7f2Tgn
  secret: 8PdV8sEkmeK13DRSM8g3WL5i7wv8Qg4hVMdSvrupSxrP
  bucket: advisio
  path: https://${aws.bucket}.hb.bizmrg.com
image:
  default: https://advisio.hb.bizmrg.com/59d1ce42-d1ec-45be-9775-cb17e34c5ea6123.jpg
server:
  port: 8181
  servlet:
    context-path: /advisio

openapi:
  security:
    scheme:
      name: default
  version: 1

springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui.html  # Изменение пути UI
    tags-sorter: alpha               # Сортировка тегов
    operations-sorter: alpha         # Сортировка методов
    oauth:
      client-id: advisio-spring-app
      client-secret: 358773
#      realm: advisio_realm
#      app-name: advisio
#      oauth2-redirect-url: "http://localhost:8181/api-docs/swagger-ui.html"
#      config-url: /api-docs/v3/api-docs
#      url: /v3/api-docs
#      use-basic-authentication-with-access-code-grant: true
  api-docs:
    path: /api-docs/v3/api-docs      # Изменение пути JSON